[package]
name = "tightness-proc"
version = "0.1.0"
authors = ["PabloMansanet <pablomansanet@gmail.com>"]
edition = "2018"
license = "MIT"

[dependencies]
syn = { version = "1.0.72", features = ["full", "fold"] }
quote = "1.0.9"

[lib]
proc-macro = true
